### ISSUE TITLE
XML directories

### ISSUE THREAD

**Issue by newton9278** [kaylh/RetroBat#1]
Bonjour,
Est-il possible d'avoir tous les fichiers xml dans un répertoire spécifique.
Par exemple : Retrobat (répertoire)\XML_roms\5200.xml; 7800.xml, etc....
Parce que le programme les mets automatiquement dans les répertoires de chaque groupe de roms 
Merci

**Comment by kaylh** [comment]
Il n'est pas possible pour l'instant de mettre les fichiers gamelist.xml dans d'autres répertoires que ceux des roms. Il s'agit du fonctionnement normal d'EmulationStation (cela fonctionne de la même manière dans les distributions retropie ou recalbox par exmple).

Je rappelle que la section "issue" de github est prévue pour recueillir les problèmes de fonctionnement ou des bugs des scripts RetroBat. Pour des questions concernant le fonctionnement général, merci d'utiliser de préférence le forum : https://retrobat.forumgaming.fr ou bien le groupe facebook : facebook.com/groups/retrobat
