### ISSUE TITLE
PCSX2 - Ne se lance pas

### ISSUE THREAD

**Issue by popo69200** [kaylh/RetroBat#11]
j'ai chargé l'émulateur dans le répertoire et les BIOS
mais quand je sélectionne un jeux ca ne le lance pas alors qu'il marche directement par l'emulateur.
Quel type de Roms est a privilégié?

**Comment by kaylh** [comment]
Alors la release de la v2.0 comportait une petite erreur de commande de ma part qui empêchait les jeux PS2 de se lancer, je l'ai corrigé et mis en ligne. Donc pour bénéficier de cette correction, à partir de la v2.0 qui comportait ce bug, il faut lancer le setup.bat, ensuite sélectionner les options suivantes : 3 - debug option, 1 - Update EmulationStation systems list, 3 - Reset EmulationStation settings. Les jeux PS2 doivent donc se lancer à nouveau.

**Comment by kaylh** [comment]
Toutefois, merci de communiquer ici en anglais, pour que les réponses soient compréhensible au plus grand nombre. Pour les personnes souhaitant s'exprimer en français, merci de préférer le forum RetroBat.
