### ISSUE TITLE
Gungames without games

### ISSUE THREAD

**Issue by pols63** [kaylh/RetroBat#113]
Hi: How I hide a system? I have the lightgun section without games.
![image](https://user-images.githubusercontent.com/53634782/219901668-90d8df3c-61fb-4f97-8a51-454b23b81511.png)

I haven't any roms too
![image](https://user-images.githubusercontent.com/53634782/219901678-148adb5a-30bb-4156-ad89-f04823cf2de1.png)

Thanks

**Comment by Tartifless** [comment]
You need to hide the lightgun collection:
https://wiki.retrobat.org/navigation/game-collections#automatic-game-collections

**Comment by pols63** [comment]
Oww!! Great! Thanks!!!
