### ISSUE TITLE
Korean Language Font Issue

### ISSUE THREAD

**Issue by soominpapa** [kaylh/RetroBat#12]
There is a problem with the display of Korean characters in emulationstation.
The default font for emulationstation does not support Korean characters. So if you set it to Korean, the normal expression will not be displayed.
I replaced it with a Korean language support font, and then normal Korean characters were displayed.
Can the Retrobats team support Korean fonts by default?

The second issue is that some characters in emulationstation are not translated into Korean.
I have modified the translation preferences file and added translation of some untranslated characters into Korean.
Some translations display normally, but some still display in English letters.

For example, letters such as menus and options are displayed in English but with Korean translations.

This did not mean I made a mistake in the translation settings.
It seems to be a problem with the program source of the emulationstation.
I request a bug fix for this.

A big thanks to the RetroBat team for developing a great frontend.

**Comment by kaylh** [comment]
Hello, thank you for your message. I'm the developper of RetroBat Scripts so I can't do this thing myself, but I forwarded your request to the developer of EmulationStation FCAMOD.
