### ISSUE TITLE
Cemu m3u file

### ISSUE THREAD

**Issue by RempelOliveira** [kaylh/RetroBat#14]
When I create a m3u file with game .rpx path, the RetroBat runs cemu, but cemu show me a alert with message saying that can't found file to execute.

**Comment by kaylh** [comment]
Hello, you need to change emulator settings to launch Wii U games. Select "cemu-m3u-launcher" in emulator settings of EmulationStation menu. 
![image](https://user-images.githubusercontent.com/30243810/78362713-db30d980-75ba-11ea-89bc-36214f7ce587.png)

**Comment by RempelOliveira** [comment]
Doesn't work. Cemu opens, but shows me the following message: The file cannot be found

**Comment by lorenzolamas** [comment]
watch me the m3u content please .
