### ISSUE TITLE
Can not download console core

### ISSUE THREAD

**Issue by sakurayz** [kaylh/RetroBat#15]
Cannot download 4do console core, the url is incorrect

**Comment by kaylh** [comment]
Hello, thank you for your report. URL are fixed now. Download again retrobat-v2.1.zip and paste files on your existing setup. Then run setup.bat, choose option 3 - Debug options, 1 - update EmulationStation systems list and 3 - Reset EmulationStation settings, then 1 -  Keep current settings. If you want to download again libretro cores, in setup.bat, choose 2 - Setup softwares, then choose option 9 or 10.
The explication is the name of 3do core "4do" changed for "opera", so the url became invalid.
All should work now.
