### ISSUE TITLE
Gamepad icons squeezed to square in 3.0

### ISSUE THREAD

**Issue by black1soarer** [kaylh/RetroBat#16]
![2020-04-25_231951](https://user-images.githubusercontent.com/64321908/80287479-56fdec00-874b-11ea-901f-b9cb270736f1.png)

**Comment by kaylh** [comment]
Hello, RetroBat v3.0 Beta is not public yet and only available on FB group so please ask your questions there. Thank you.

**Comment by kaylh** [comment]
Hello, new update of ES fixed this issue.
