### ISSUE TITLE
Themes for RetroBat have spacing issues 

### ISSUE THREAD

**Issue by striderhiryux99** [kaylh/RetroBat#17]
I just wanted to mention that some of the themes for EmulationStation (when using the Retrobat version) appear to have spacing issues. As an example, take a look at my NES page in the SNES-Mini theme:

https://drive.google.com/file/d/1FtiW3227m3YUUQPrcsO4gkb7zowxq-Rp/view?usp=sharing

Is there any way to make adjustments to any settings to fix these issues? It also effects the way text in some of the words appear on the screen (in my Comic Book theme, the word "Favorites" is truncated to "Favoris" and you can barely read the word "Choose" on the bottom of the screen.)

Thank you for your input :-).

**Comment by kaylh** [comment]
Hello, you are using old theme made for RetroPie branch of EmulationStation. This need an overhaul of the theme to be fully compatible with RetroBat ES or Batocera. Look at this documentation as reference to update themes xml : https://github.com/fabricecaruso/EmulationStation/blob/master/THEMES.md

**Comment by fabricecaruso** [comment]
Not a spacing issue : Screen resolution is set to 4:3 when the theme is designed to 16:9 -> Just fix your screen resolution.

**Comment by striderhiryux99** [comment]
Just a quick question to Fabrice. What dimensions should I add to the
config file to change the resolution to 16:9? My TV is 1024x768. I would
like the screen to show the developer and publisher on the left side, along
with the description, the cover art, and icon rating on the right side. The
name of each game should appear in the center. Right now, I was able to get
the cover art and icon rating on the left, and the name of each game on the
right side, but the placeholder or bar at the bottom of the screen has no
title.

Thank you for your help 😀.
