### ISSUE TITLE
comment utiliser le repertoire medias

### ISSUE THREAD

**Issue by newton9278** [kaylh/RetroBat#2]
Bonjour,
Comment utiliser le répertoire "médias" pour que toutes les vidéos, images soit prises en comptent avec par exemple : 
médias\atari5200\vidéo or snap\*.mp4
médias\atari5200\wheel\*.png
médias\atari5200\boxart\*.png

car par défaut il cré les répertoires dans le répertoires des roms
Merci

**Comment by kaylh** [comment]
Bonjour. Le répertoire médias est pour la lecture de vidéos par le core libretro "ffmpeg". Il est donc prévu pour y mettre des films par exemple pour les lire en allant dans le menu médias de EmulationStation et non pour les preview video des jeux. Il n'est pas possible pour l'instant d'avoir les fichiers de preview video et les images de boitier dans un autre répertoire que celui des roms (c'est le scrapper intégré d'EmulationStation qui crée ces dossiers).

Je rappelle que la section "issue" de github est prévue pour recueillir les problèmes de fonctionnement ou des bugs des scripts RetroBat. Pour des questions concernant le fonctionnement général, merci d'utiliser de préférence le forum : https://retrobat.forumgaming.fr ou bien le groupe facebook : facebook.com/groups/retrobat
