### ISSUE TITLE
v3.0 Beta if running ps2 game, hotkey can't exit retrun to ES

### ISSUE THREAD

**Issue by xbox2233** [kaylh/RetroBat#21]
when running ps2 game pcsx2 v1.6 , game is full speed and nice, but I can't use hotkey or select+start exit and return to ES. Only use keyboard ESC can do it, but maybe full use joystcik to control is best way...

Is this a bug?

**Comment by kaylh** [comment]
Hello. Not a bug but a limitation of pcsx2. No hotkey features to close the emulator. So we planned to add this possibility that will be available with the new stable release of RetroBat.

**Comment by xbox2233** [comment]
wooooo... that sounds good , thank you very much
