### ISSUE TITLE
Prevent Retrobat from Changing Retroarch config (such as global config option, menu driver, etc)

### ISSUE THREAD

**Issue by buddwm** [kaylh/RetroBat#27]
It seems there is some sort of hook in Retrobat that auto enables the global config option in Retroarch.  I've tried disabling this, but no matter what I try, I can't get Retrobat to stop turning the option back on.  On top of that, Retrobat seems to change other Retroarch options automatically, like which menu driver to use.  There doesn't seem to be any documentation around this, so how does one disable Retrobat from changing Retroarch options like global config, menu driver, etc?  I am using 3.10 stable.

**Comment by kaylh** [comment]
Hello, you can disable config files check by editing retrobat.ini and set ConfigMode to 0. But this is not recommended as many emulators options are integrated in ES menu.

**Comment by buddwm** [comment]
That doesn't seem to work.  When I change it to 0, I still find that it changes the menu driver for retroarch among other things.  The only workaround I've found is to launch emulationstation by itself, but even this doesn't allow me to select my own menu driver in retroarch...
