### ISSUE TITLE
Horizontal line on display

### ISSUE THREAD

**Issue by 4gordi** [kaylh/RetroBat#28]
Hello, everyone, i have a problem. After install on my notebook (intel core i3, intel hd520, 16gb ram) retrobat, and start the emulation system, on display horizontal line 
![problem](https://user-images.githubusercontent.com/27728217/88137870-2b2cbe00-cbf5-11ea-8d1c-b3c3086ab091.png)
but after exit the retrobat in windows 10 all right, what could be wrong?

**Comment by kaylh** [comment]
Hello, it seems to be a DPI scaling issue. Right-click on emulationstation.exe and select "properties". Select "Compatibility" then click on "High DPI settings". In the new displayed window, check the first box under "Program DPI" then select in the combo box "I open this program". Check the box under "High DPI scaling override" and click OK. Then try to launch retrobat.Exe again. If this not resolve your problem, check the dependancies needed for retrobat and emulators (direct3d, visual c++ 2010, 2015,2017,2019) and the CG driver (in your case, intel hd graphics drivers).

**Comment by 4gordi** [comment]
It's worked)) i'm so happy) thanx
