### ISSUE TITLE
Cant download ?

### ISSUE THREAD

**Issue by Xephilor** [kaylh/RetroBat#3]
Hello !
RetroBat v1.20.2 send an error message in Powershell  when installing :
![2019-11-26 133742](https://user-images.githubusercontent.com/58218185/69634190-ff4f3d80-1051-11ea-97b0-237d51ce05dd.jpg)

On Windows 10 64 version 1909
Merci et bravo encore pour ce travail auquel j'ai hâte de goûter !

**Comment by kaylh** [comment]
Hello, thank you for your message. This error may occure because of unavailable server or during maintenance. You should be able to download now.

**Comment by Xephilor** [comment]
Thank you for your answer.
But automatic and manual install give me same error message now.

**Comment by kaylh** [comment]
Are you sure you have enabled execution of powershell script ? This should be enabled by default but if not, open powershell terminal with administrator rights and paste this command:
` Set-ExecutionPolicy RemoteSigned`
Then type enter.
