### ISSUE TITLE
There is some problem launching setup from a folder with spaces

### ISSUE THREAD

**Issue by bleuge** [kaylh/RetroBat#4]
I unpacked everything to c:/Gog games/retrobat and launched setup:

```
"\GOG" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"\GOG" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
          Version setup_dir=\GOG Games\noahs Games\noahs\System\retrobat.setup Games\noahs\System\retrobat.setup by Kayl
+===========================================================+
 ( 1 ) -- Launch EmulationStation
```

Also, why the need for launching setup non-admin ? 

thanks! I love this tool!

**Comment by kaylh** [comment]
The need for launching setup without admin right is to allow RetroBat to setup in portable mode (to be launched from removable devices) and this prevents the use of RetroBat from being diverted to affect the user's root system.
For the impossibility for RetroBat to be setup in a folder containing spaces, it will be corrected in the next version of RetroBat, whivh will be released in few days.

**Comment by bleuge** [comment]
Thanks!, I installed in c:\retrobat and worked perfect, thanks!
