### ISSUE TITLE
[Suggestion] Maybe es_resolution_* vars could auto update at first run?

### ISSUE THREAD

**Issue by bleuge** [kaylh/RetroBat#5]
I tested this in my Thinkpad, so after some google searching I found where you set up those vars, as I was getting off-screen rendering.

I don't know a thing about powersell, but maybe there is a way to autodetect current active monitor resolution and auto fill them in the emulationstation.cfg file ?
These worked in my x240:

es_resolution_width=1366
es_resolution_height=768

Thanks!

edit: Showing a submenu in setup, offering different valid resolutions for active monitor will be much better :D

**Comment by beneva52** [comment]
[retrobat-scripts.zip](https://github.com/kaylh/RetroBat/files/3965563/retrobat-scripts.zip)
Download the attached zip file and put "ini.bat" and "MonitorConfig.cmd" in your /RetroBat/system/scripts folder.
Then modify /RetroBat/setup.bat and after line 590, add the 2 following lines:
set scripts_dir=%scripts_path%
call %scripts_dir%\MonitorConfig.cmd 
If you try version 2 beta 1, just add the following line after line 76:
call %scripts_dir%\MonitorConfig.cmd 
It should do the trick :)

**Comment by bleuge** [comment]
Never thought I could setup a ES+RA so easy in windows, thanks you very much!
