### ISSUE TITLE
Plein écran

### ISSUE THREAD

**Issue by beneva52** [kaylh/RetroBat#6]
Bonjour, lorsque je lance un jeu, puis que je le quitte, ES ne se remet pas en plein écran, il clignote dans la barre des tâches. Je dois cliquer dessus pour qu'il se remette en plein écran, ce qui n'est pas très pratique.
Avez-vous le même problème ?

**Comment by kaylh** [comment]
Bonjour, effectivement depuis les dernières maj de ES il semble que la fenêtre ne fait pas le focus sur ES après avoir quitté un jeu. J'ai pas la main sur EmulationStation, mais j'ai remonté ce problème au développeur de ES avec qui nous collaborons pour RetroBat. En attendant, on peut contourner ce désagrément en activant une option dans le menu de ES, dans option de l'interface, activer "masquer au démarrage".

**Comment by beneva52** [comment]
Effectivement, ça marche. Merci !
As-tu regardé ma solution pour l'issue#5 ?

**Comment by beneva52** [comment]
Il faudrait rajouter la ligne suivante dans es_settings.cfg pour le problème de focus
`<bool name="HideWindow" value="true" />`

**Comment by kaylh** [comment]
Oui j'ai vu ton script pour modifier le emulationstation.cfg automatiquement, c'est pratique oui. Mais on n'est pas obligé par contre d'utiliser retro.bat pour que emulationstation fonctionne. En lançant le binaire de ES, il se lance avec la résolution détectée. Pour la v1.20.2 on ne peut pas lancer les autres scripts dans ES, mais avec la future v2.0 j'ai corrigé cela. retro.bat devient totalement facultatif. J'ai vu que tu avais testé la béta, il risque d'y avoir qq bugs (quoique, elle est sans doute plus stable et mieux écrite que l'ancienne version) mais surtout qq changements avant la release.
