### ISSUE TITLE
V5 beta video playback glitches on Windows 11 Intel 12th gen Iris Xe GPU

### ISSUE THREAD

**Issue by luke-70it** [kaylh/RetroBat#81]
All videos in Retrobat (intro video and game previews) start corrupted and after a couple seconds are rendered correctly. I attach a screenshot of  a video preview corrupted.
If a play videos directly in Windows, they play fine from the beginning.
![NES - 1943](https://user-images.githubusercontent.com/54847115/198309503-e9273e5b-022d-4466-97f2-3850acac80ef.jpg)

**Comment by kaylh** [comment]
Hello,
This bug is related to the VLC library version and plugins that EmulationStation use and occurs generally on slow storage devices. There is no plan for now to update the VLC library and plugins.

**Comment by luke-70it** [comment]
Thank you very much!
