### ISSUE TITLE
 RetroBat Portable

### ISSUE THREAD

**Issue by candrapersada** [kaylh/RetroBat#82]
why is there no clear information on how to use RetroBat Portable?
and why is there no RetroBat Portable version zip in the [download menu](https://www.retrobat.ovh/dl_en.html)?

**Comment by kaylh** [comment]
You don't need a "portable version" because RetroBat is already portable as it is. You can install it on any storage and use it on any computer that meets the requirements.

**Comment by candrapersada** [comment]
how to install it on any storage device?

**Comment by kaylh** [comment]
Just use the setup program and select the path to your storage device...
