### ISSUE TITLE
MUGEN - type de rom

### ISSUE THREAD

**Issue by popo69200** [kaylh/RetroBat#9]
Bonjour j'ai des rom fonctionnelles sur HS pour MUGEN mais c'est un repertoire avec pleins de fichiers. RETROBAT est compatible avec quel type de ROM svp?

**Comment by kaylh** [comment]
MUGEN n'est pas une roms mais un logiciel Windows qui est un moteur de déveoppement pour concevoir des jeux de combats 2D. Ces jeux sont distribués au format binaire Windows 32bits, donc ce sont généralement des dossiers qui contiennent les données des jeux et un fichier exécutable .exe. A placer dans le dossier mugen des roms.

Toutefois, merci de réserver la section issues de github au problème de fonctionnement de RetroBat. Et de communiquer ici en anglais, pour que les réponses soient compréhensible au plus grand nombre. Pour les personnes souhaitant poser des questions sur le fonctionnement, merci de préférer le groupe facebook ou le forum (ce dernier étant réservé à la communauté francophone).
