### ISSUE TITLE
v5.0 Sega 32x core (picodrive) not displaying achievements 

### ISSUE THREAD

**Issue by sammy2142** [kaylh/RetroBat#94]
Hello
When loading a 32x game via retrobat, achievements do not work. The achievements menu is actually missing in the quick menu.
The achievements work fine running a standalone copy of retroarch with picodrive.

Kind Regards

**Comment by kaylh** [comment]
Hello, sorry for this very late answer. The dev team is more active on discord or the forum. This is fixed in the latest versions of RetroBat.
