### ISSUE TITLE
Add BigPEmu if possible

### ISSUE THREAD

**Issue by Dovey79** [kaylh/RetroBat#96]
I know it's only been released about a week but it seems a very competent Atari Jaguar emulator. Author claims 100% compatibility and I can't prove otherwise yet.

It supports loading roms from command line and individual rom settings.

Reshade also works to add bezel.

Exit can be performed by alt f4.

Could you please think about adding this so it could be officially supported by retrobat?
I am happy to help in any way.
Thanks.

**Comment by Tartifless** [comment]
Unfortunately the emulator is not portable (config file is stored in %APPDATA%\ROAMING\BIGPEMU.

Until the config file can be stored somewhere else there is no possibility to add it yet.

**Comment by Dovey79** [comment]
Thank you for your time and effort. 

Rich has now very kindly updated bigpemu to v1.03. Command line option now supports local storage of config where the exe is.

'bigpemu.exe %ROM% -localdata'

Hope this helps. Thanks again :)

**Comment by Tartifless** [comment]
Hello, yes we have contacted Rich and he did it.
We had already integrated it and the code will be ready for next version.

**Comment by Tartifless** [comment]
We can close this now.
