### ISSUE TITLE
CDI bezel

### ISSUE THREAD

**Issue by Dovey79** [kaylh/RetroBat#97]
Same_cdi core seems to have generated some interest in this system recently. I have not seen any update for batocera to include the bezel in default unglazed. This is the closest I have to the default and you can include it if you want.

![cdi](https://user-images.githubusercontent.com/120262130/209735329-3bec829e-618d-483f-a70c-6ad9d7389d82.png)

If not then please just close this issue.
As ever, many thanks for all the time and effort dedicated to retrobat :)

**Comment by kaylh** [comment]
Hello, sorry for this very late answer. The dev team is more active on discord or the forum. Thank you for proposing us this file. The latest version of RetroBat include bezel for CDI.
